projeto-diam/ProjetoDIAM/ProjetoDIAM/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('review/', include('reviews.urls')),
    path('admin/', admin.site.urls),
]

projeto-diam/ProjetoDIAM/reviews/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'reviews'
urlpatterns = [
    path("", views.homepage, name='homepage'),
    path('search', views.search, name='search'),
    path('search/<int:gender_id>', views.search_gender, name='search_gender'),
    path('profile/<int:profile_id>', views.profile, name='profile'),
    path('follow/<int:reviewer_id>', views.follow, name='follow'),
    path('unfollow/<int:reviewer_id>', views.unfollow, name='unfollow'),
    path('login_register', views.login_register, name='login_register'),
    path('loginview', views.loginview, name='loginview'),
    path('registerview', views.registerview, name='registerview'),
    path('logoutview', views.logoutview, name='logoutview'),
    path('review/<int:review_id>', views.review, name='review'),
    path('createreview', views.createreview, name='createreview'),
    path('review/<int:review_id>/deletereview', views.deletereview, name='deletereview'),
    path('deletecomment/<int:comment_id>', views.deletecomment, name='deletecomment'),
    path('editar_perfil', views.editar_perfil, name='editar_perfil'),
    path('termsofservice', views.termsofservice, name='termsofservice'),
    path('aboutus', views.aboutus, name="aboutus"),
    path('contact', views.contact, name="contact"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projeto-diam/ProjetoDIAM/reviews/models.py
from django.db import models
from django.utils import timezone
from six import string_types
import datetime
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator

class Review(models.Model):
    review_title = models.CharField(max_length=200)
    pub_data = models.IntegerField(default=2023)
    photo = models.CharField(max_length=500)
    overview = models.CharField(max_length=1000, default='')
    avg_rating = models.IntegerField(default=0)

    def str(self):
        return self.review_title

class Reviewer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.CharField(max_length=250, default="/static/reviews/media/default.png")
    following = models.ManyToManyField('self', symmetrical=False, related_name='followers', blank=True)

class Comment(models.Model):
    comment_text = models.CharField(max_length=500)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    pub_data = models.DateTimeField('data de publicacao')
    reviewer = models.ForeignKey(Reviewer, on_delete=models.CASCADE, default=None)

    def str(self):
        return self.comment_text

class Gender(models.Model):
    gender_category = models.CharField(max_length=100)
    reviews = models.ManyToManyField(Review)

    def str(self):
        return self.gender_category

class Rating(models.Model):
    rating_number = models.IntegerField(default=0, validators=[MaxValueValidator(5)])
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    reviewer = models.ForeignKey(Reviewer, on_delete=models.CASCADE, default=None)

    def str(self):
        return self.rating_number

projeto-diam/ProjetoDIAM/reviews/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from .models import Review, Gender
from django.contrib.auth import authenticate, login, logout, models
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.urls import reverse
from .models import Reviewer, Comment, Rating
from django.db.models import Avg
from django.core.files.storage import FileSystemStorage
from django.utils import timezone
from django.contrib.auth.hashers import check_password


def homepage(request):
    latest_review_list = Review.objects.order_by('-pub_data')
    context = {'latest_review_list': latest_review_list}
    gender_list = Gender.objects.order_by('gender_category')
    context1 = {'gender_list': gender_list}
    context.update(context1)
    for review in latest_review_list:
        review.avg_rating = review.rating_set.all().aggregate(Avg('rating_number'))['rating_number__avg']
    if request.user.is_authenticated:
        current_reviewer = Reviewer.objects.get(user=request.user)
        following_reviewers = current_reviewer.following.all()
        following_comments = Comment.objects.filter(reviewer__in=following_reviewers).order_by('-pub_data')
        context2 = {'following_comments': following_comments}
        context.update(context2)
        return render(request, 'reviews/homepage.html', context)
    else:
        return render(request, 'reviews/homepage.html', context)


def search(request):
    reviews = Review.objects.all()
    reviewers = Reviewer.objects.all()
    gender_list = Gender.objects.order_by('gender_category')
    context = {'gender_list': gender_list}
    search_reviews = []
    search_reviewers = []
    search_gender = []
    if request.method == 'POST':
        search = request.POST['search']
        context1 = {'search': search}
        context.update(context1)
        for review in reviews:
            if search.lower() in review.review_title.lower():
                search_reviews.append(review)
        context2 = {'search_reviews': search_reviews}
        context.update(context2)
        for reviewer in reviewers:
            if search.lower() in reviewer.user.username.lower():
                search_reviewers.append(reviewer)
        context3 = {'search_reviewers': search_reviewers}
        context.update(context3)
        for gender in gender_list:
            if search.lower() == gender.gender_category.lower():
                for review in gender.reviews.all():
                    search_gender.append(review)
        context4 = {'search_gender': search_gender}
        context.update(context4)
        return render(request, 'reviews/search.html', context)
    return render(request, 'reviews/search.html', context)


def search_gender(request, gender_id):
    gender_list = Gender.objects.order_by('gender_category')
    context = {'gender_list': gender_list}
    gender = Gender.objects.get(id=gender_id)
    search = gender.gender_category
    context2 = {'search': search}
    context.update(context2)
    search_gender = []
    for review in gender.reviews.all():
        search_gender.append(review)
    context3 = {'search_gender': search_gender}
    context.update(context3)
    return render(request, 'reviews/search.html', context)


def login_register(request):
    return render(request, 'reviews/login.html')


def review(request, review_id):
    review = get_object_or_404(Review, pk=review_id)
    context = {'review': review}
    comments = Comment.objects.filter(review=review)
    context1 = {'comments': comments}
    context.update(context1)
    gender_list = Gender.objects.order_by('gender_category')
    context2 = {'gender_list': gender_list}
    context.update(context2)
    review.avg_rating = review.rating_set.all().aggregate(Avg('rating_number'))['rating_number__avg']
    if request.method == 'POST':
        for comment in comments:
            if comment.reviewer.id == request.user.reviewer.id:
                context3 = {'error_message': "This User already commented this movie!"}
                context.update(context3)
                return render(request, 'reviews/review.html', context)

        try:
            comment_text = request.POST['comment_text']
            rating_number = request.POST['rating']
            if rating_number == "":
                context3 = {'error_message': "Rate the movie first!"}
                context.update(context3)
                return render(request, 'reviews/review.html', context)
            user = request.user
            reviewer = Reviewer.objects.get(user=user)
            rating = Rating(rating_number=rating_number, review=review, reviewer=reviewer)
            rating.save()
            comment = review.comment_set.create(comment_text=comment_text, review=review, pub_data=timezone.now(),
                                                reviewer=reviewer)
            comment.save()
        except KeyError:
            # Redisplay the form with an error message
            return render(request, 'reviews/review.html', {'error_message': "Não escreveu nenhum comentário"})
        else:
            return HttpResponseRedirect(reverse('reviews:review', args=(review.id,)))
    else:
        return render(request, 'reviews/review.html', context)


def createreview(request):
    gender_list = Gender.objects.order_by('gender_category')
    context = {'gender_list': gender_list}
    if request.method == 'POST':
        review_title = request.POST['review_title']
        pub_data = request.POST['pub_data']
        overview = request.POST['overview']
        review = Review(review_title=review_title, pub_data=pub_data, overview=overview)
        review.save()
        genres = request.POST.getlist('opcoes')
        for genre in genres:
            genre = Gender.objects.get(gender_category=genre)
            genre.reviews.add(review)
        if 'myfile' in request.FILES:
            print("olá")
            myfile = request.FILES['myfile']
            fs = FileSystemStorage()
            filename = fs.save(myfile.name, myfile)
            uploaded_file_url = fs.url(filename)
            review.photo = uploaded_file_url.replace('/reviews', '', 1)
            review.save()
        return HttpResponseRedirect(reverse('reviews:homepage'))
    else:
        return render(request, 'reviews/createreview.html', context)


def loginview(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            # direccionar para página de sucesso
            return HttpResponseRedirect(reverse('reviews:homepage'))
        else:
            # direccionar para página de insucesso
            return render(request, 'reviews/login.html',
                          {'error_message': "Incorrect Username or Password, please insert the right inputs!"})
    else:
        return render(request, 'reviews/login.html')

def registerview(request):
    try:
        new_username = request.POST['new_username']
        new_password = request.POST['new_password']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        if (new_username == "" or first_name == "" or last_name == "" or email == "" or new_password == ""):
            return render(request, 'reviews/login.html', {'error_message': "Por favor preencha todos os campos."})
        elif (len(new_username) > 15):
            return render(request, 'reviews/login.html', {'error_message': "O username não pode conter mais de 15 caracteres"})
        elif ( " " in new_username):
            return render(request, 'reviews/login.html', {'error_message': "O nome de utilizador não pode conter espaços em branco."})
        elif ( not "@" in email or not "." in email):
            return render(request, 'reviews/login.html', {'error_message': "Introduza um email válido"})
        elif (len(new_password) < 8):
            return render(request, 'reviews/login.html', {'error_message': "A senha deve ter pelo menos 8 caracteres."})
        u = User.objects.create_user(username=new_username, email=email, password=new_password, first_name=first_name,
                                     last_name=last_name)
        u.save()
        ut = Reviewer(user=u)
        ut.save()
    except KeyError:
        # Redisplay the form with an error message
        return render(request, 'reviews/login.html', {'error_message': "Não escreveu nenhuma opção"})
    else:
        if u is not None:
            login(request, u)
        return HttpResponseRedirect(reverse('reviews:homepage'))

def logoutview(request):
    logout(request)
    return HttpResponseRedirect(reverse('reviews:homepage'))


def profile(request, profile_id):
    reviewer = get_object_or_404(Reviewer, pk=profile_id)
    context = {'reviewer': reviewer}
    user_comments = Comment.objects.filter(reviewer=reviewer)
    context1 = {'user_comments': user_comments}
    context.update(context1)
    if request.user.is_authenticated:
        user = request.user.reviewer
        exists = user.following.filter(id=reviewer.id).exists()
        context2 = {'exists': exists}
        context.update(context2)
    return render(request, 'reviews/profile.html', context)


def editar_perfil(request):
    if request.method == 'POST':
        user = request.user
        new_first_name = request.POST['first_name']
        user.first_name = new_first_name
        new_last_name = request.POST['last_name']
        user.last_name = new_last_name
        new_email = request.POST['email']
        user.email = new_email
        current_password = request.POST['current_password']
        new_password = request.POST['new_password']
        user.save()

projeto-diam/ProjetoDIAM/reviews/templates/reviews/createreview.html
{% extends "./homepage.html" %}

{% block titulo %}
Create Review
{% endblock %}

{% block header %}
{% endblock %}

{% block conteudo %}
<div class="create-review">

    <h2>Crie Review</h2>
    <form method="post" enctype="multipart/form-data" action="{% url 'reviews:createreview' %}">
        {% csrf_token %}
        <label for="review_title">Title:</label>
        <input type="text" id="review_title" name="review_title"><br><br>
        <label for="pub_data">Publication Year:</label>
        <input type="number" id="pub_data" name="pub_data"><br><br>
        <label for="opcoesSelecionadas">Category:</label>
        <input type="text" id="opcoesSelecionadas" name="opcoesSelecionadas" readonly onclick="exibirOpcoes()">
        <br>
        <div id="opcoesCheckbox" style="display: none;">
            {% for genre in gender_list %}
            <input type="checkbox" id="opcao{{ genre.gender_category }}" name="opcoes"
                   value="{{ genre.gender_category }}" onclick="atualizarOpcoesSelecionadas()">
            <label for="opcao{{ genre.gender_category }}">{{ genre.gender_category }}</label>
            <br>
            {% endfor %}
        </div>
        <label for="overview">Overview:</label>
        <input type="text" id="overview" name="overview"><br><br>
        {% csrf_token %}
        <input type="file" name="myfile"><br><br>
        <input type="submit" value="Submit">
    </form>
</div>
{% endblock %}

projeto-diam/ProjetoDIAM/reviews/templates/reviews/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>
        {% block titulo %}
            FlixFeed
        {% endblock %}
    </title>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'reviews/css/style.css' %}?{% now "U" %}">
    <link rel="stylesheet" type="text/css"
          href="{% static 'reviews/css/font-awesome-4.7.0/css/font-awesome.min.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="{% static 'reviews/scripts/script.js' %}?{% now "U" %}"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com%22%3E/">
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kumbh+Sans:wght@400;700&display=swap" rel="stylesheet">

</head>

<body>

<header>

    <div class="logo">
        <a href="{% url 'reviews:homepage' %}">
            <img src="/static/reviews/media/flixfeed.png" alt="symbol" width="150px" height="50px">
        </a>
    </div>

    {% block header %}
        <div class="search-bar">
            <form method="post" action="{% url 'reviews:search' %}">
                {% csrf_token %}
                <input type="text" id="search" name="search" placeholder="Search...">
                <button type="submit"><i></i>Search</button>
            </form>
        </div>

        <div class="sidebar">
            <br><br><br>
            <p>Genres:</p>
            <ul>
                {% for gender in gender_list %}
                    <li>
                        <a href="{% url 'reviews:search_gender' gender.id %}">{{ gender.gender_category }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <button class="sidebar_button" id="toggle-sidebar">&#9776;</button>
    {% endblock %}

    {% block profile %}

        {% if request.user.is_authenticated %}
            <ul>
                <li class="user-profile">
                    <div class="dropdown">
                        <p class="username">{{ request.user.username }}</p>
                        <img src="{{ request.user.reviewer.photo }}" class="profile-pic pic" alt="Foto de perfil"
                             width="50px"
                             height="50px">
                        <div class="dropdown-content">
                            <a href="{% url 'reviews:profile' request.user.reviewer.id %}"
                               class="profile-btn">Profile</a>
                            <a href="{% url 'reviews:logoutview' %}" class="logout-btn">Logout</a>
                        </div>
                    </div>
                </li>
            </ul>
        {% else %}
            <ul>
                <li>
                    <a href="{% url 'reviews:login_register' %}" class="login-btn">Login</a>
                </li>
            </ul>
        {% endif %}
    {% endblock %}
</header>

<main>

    {% block conteudo %}
        {% if request.user.is_superuser %}
            <a href="{% url 'reviews:createreview' %}" class="create-review-btn">Add Movie</a>
        {% endif %}

        <div class="mainHeader">
            <p class="selected" id="toggle-foryou">For you</p>
            {% if request.user.is_authenticated %}
                <p id="toggle-following">Following</p>
            {% endif %}
        </div>

        <div class="foryou">
            {% if latest_review_list %}
                <ul>
                    {% for review in latest_review_list %}
                        <li>
                            <div class="homepage-review">
                                <img src="{{ review.photo }}" class="review-photo">
                                <div class="title-genre">
                                    <a href="{% url 'reviews:review' review.id %}"> {{ review.review_title }} </a>
                                    <div class="genres-container">
                                        {% for gender in review.gender_set.all %}
                                            <a href="{% url 'reviews:search_gender' gender.id %}">{{ gender.gender_category }}
                                                {% if not forloop.last %}, {% endif %}</a>
                                        {% endfor %}
                                    </div>
                                </div>
                                <br>
                                <p class="overview"><strong>Overview:</strong> {{ review.overview }}</p>
                                <p class="rating">Rating: {{ review.avg_rating }}</p><br>
                                {% if request.user.is_superuser %}
                                    <form action="{% url 'reviews:deletereview' review.id %}" method="get">
                                        <button type="submit" class="delete-button-rvw">
                                            <i class="fa fa-trash"></i>
                                        </button>
                                    </form>
                                {% endif %}
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>There are no reviews available.</p>
            {% endif %}
        </div>

        {% if request.user.is_authenticated %}
            <div class="following-content">
                <ul>
                    {% for comment in following_comments %}
                        <li>
                            <div class="following-box">
                                <a href="{% url 'reviews:profile' comment.reviewer.id %}" class="user-profile-pic">
                                    <img src="{{ comment.reviewer.photo }}" class="pic">
                                    {{ comment.reviewer.user.username }}
                                </a>
                                <br>
                                <a href="{% url 'reviews:review' comment.review.id %}"><strong>{{ comment.review.review_title }}</strong></a>
                                <p class="user-comments-date">{{ comment.pub_data }}</p>
                                <p>{{ comment.comment_text }}</p>
                                {% for rating in comment.review.rating_set.all %}
                                    {% if rating.reviewer.id == comment.reviewer.id %}
                                        <p>Rating: {{ rating.rating_number }}</p>
                                    {% endif %}
                                {% endfor %}
                                {% if request.user.is_superuser %}
                                    <form action="{% url 'reviews:deletecomment' comment.id %}" method="get">
                                        <button type="submit" class="delete-button-rvw">
                                            <i class="fa fa-trash"></i>
                                        </button>
                                    </form>
                                {% endif %}
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        <br><br><br>

        </main>

        <footer>
            <div class="footer-container">
                <div class="footer-links">
                    <div class="footer-link-wrapper">
                        <div class="footer-link-items">
                            <h2>About Us</h2>
                            <a href="{% url 'reviews:aboutus' %}">How it works</a>
                            <a href="{% url 'reviews:termsofservice' %}">Terms of Service</a>
                        </div>
                        <div class="footer-link-items">
                            <h2>Contact Us</h2>
                            <a href="{% url 'reviews:contact' %}">Contact</a>
                        </div>
                    </div>
                </div>
                <div class=" social-media">
                    <div class="social-media--wrap">
                        <p class="footer-logo"> FlixFeed</p>
                        <p class="website-rights">© FlixFeed 2023. All rights reserved</p>

                    </div>
                </div>
            </div>
        </footer>
        </body>
    {% endblock %}
</html>

projeto-diam/ProjetoDIAM/reviews/templates/reviews/login.html
{% extends "./homepage.html" %}

{% block titulo %}
    Login
{% endblock %}

{% block header %} {% endblock %}

{% block profile %} {%  endblock %}

{% block conteudo %}
    <script>
        {% if error_message %}
            window.alert("{{ error_message }}")
        {% endif %}
    </script>

    <div class="container">
        <form id="login-form" class="form" action="{% url 'reviews:loginview' %}" method="post">
            {% csrf_token %}
            <h2>Login</h2>

            <label for="username">Nome de utilizador:</label>
            <input type="text" id="username" name="username"><br>
            <label for="password">Password:</label>
            <input type="password" id="password" name="password"><br>
            <button class="form-submit-button" type="submit">Login</button>
            <h4>Ainda não tem conta?</h4>
            <div class="form-group">
                <input type="checkbox" id="register-checkbox">
                <label for="register-checkbox">Registe-se aqui!</label>
            </div>
        </form>

        <form id="register-form" class="form hidden" action="{% url 'reviews:registerview' %}" method="post">
            {% csrf_token %}
            <h2>Registo</h2>
            <label for="new_username">Nome de utilizador:</label>
            <input type="text" id="new_username" name="new_username"><br>
            <label for="first_name">Nome:</label>
            <input type="text" id="first_name" name="first_name"><br>
            <label for="last_name">Apelido:</label>
            <input type="text" id="last_name" name="last_name"><br>
            <label for="email">Email:</label>
            <input type="email" id="email" name="email"><br>
            <label for="new_password">Password:</label>
            <input type="password" id="new_password" name="new_password"><br>
            <button class="form-submit-button" type="submit">Registo</button>
            <h4>Já tem conta?</h4>
            <div class="form-group">
                <input type="checkbox" id="login-checkbox">
                <label for="login-checkbox">Faça o seu Login.</label>
            </div>
        </form>
    </div>
{% endblock %}

projeto-diam/ProjetoDIAM/reviews/templates/reviews/profile.html
{% extends "./homepage.html" %}

{% block titulo %}
    Perfil
{% endblock %}

{% block header %}
    {% if request.user.is_authenticated %}
        {% if request.user.reviewer.id == reviewer.id %}
            <a href="{% url 'reviews:editar_perfil' %}" class="edit-profile-btn">Edit</a>
        {% else %}
        {% endif %}
    {% endif %}
{% endblock %}

{% block conteudo %}
    <div class="profile">
        <div class="profile-header">
            {% if request.user.reviewer.id != reviewer.id and request.user.is_authenticated %}
                {% if exists %}
                    <a href="{% url 'reviews:unfollow' reviewer.id %}" class="follow-unfollow-btn">Unfollow</a>
                {% else %}
                    <a href="{% url 'reviews:follow' reviewer.id %}" class="follow-unfollow-btn">Follow</a>
                {% endif %}
            {% endif %}
            <h1>Username: {{ reviewer.user.username }}</h1>
        </div>
        <br>
        <div class="user-info">
            <a>Email: {{ reviewer.user.email }}</a>
            <br>
            <a>First Name: {{ reviewer.user.first_name }}</a>
            <br>
            <a>Last Name: {{ reviewer.user.last_name }}</a>
            <br><br>
        </div>
        <div class="user-info-pic">
            <img src="{{ reviewer.photo }}" alt="Foto de perfil">
        </div>
    </div>

    <div class="user-comments">
        {% for comment in user_comments %}
            <div class="between-comments">
                <a href="{% url 'reviews:profile' reviewer.id %}" class="user-profile-pic">
                    <img src="{{ comment.reviewer.photo }}" class="pic">
                    {{ comment.reviewer.user.username }}
                </a>
                <br>
                <a href="{% url 'reviews:review' comment.review.id %}"><strong>{{ comment.review.review_title }}</strong></a>
                <p class="user-comments-date">{{ comment.pub_data }}</p>
                <p>{{ comment.comment_text }}</p>
                {% for rating in comment.review.rating_set.all %}
                    {% if rating.reviewer.id == comment.reviewer.id %}
                        <p>Rating: {{ rating.rating_number }}</p>
                    {% endif %}
                {% endfor %}
                {% if request.user.is_superuser or request.user.username == comment.reviewer.user.username %}
                    <form action="{% url 'reviews:deletecomment' comment.id %}" method="get">
                        <button type="submit" class="delete-button">
                            <i class="fa fa-trash"></i>
                        </button>
                    </form>
                {% endif %}
            </div>
        {% endfor %}
    </div>


{% endblock %}

projeto-diam/ProjetoDIAM/reviews/templates/reviews/review.html
{% extends "./homepage.html" %}

{% block titulo %}
{{ review.review_title }}
{% endblock %}

{% block conteudo %}
<div class="review">
    <ul>
        <li>
            <div class="review-main-div">
                <img src="{{ review.photo }}" class="review-photo">
                <div class="title-genre">
                    <a href="{% url 'reviews:review' review.id %}"> {{ review.review_title }} </a>
                    <div class="genres-container">
                        {% for gender in review.gender_set.all %}
                        <a href="{% url 'reviews:search_gender' gender.id %}">{{ gender.gender_category }}
                            {% if not forloop.last %}, {% endif %}</a>
                        {% endfor %}
                    </div>
                </div>
                <br>
                <p class="overview-review"><strong>Overview: </strong>{{ review.overview }}</p>
                <p class="rating">Rating: {{ review.avg_rating }}</p><br>
            </div>
            <br>
        </li>
    </ul>
</div>

{% if request.user.is_authenticated %}

<form action="{% url 'reviews:review' review.id %}" method="post">
    {% csrf_token %}
    <div class="comment-input-container">
        <input type="number" name="rating" id="rating" style="display: none">
        <input type="text" name="comment_text" id="comment_text" placeholder="Comment...">
        <button type="submit">Comment</button>
        <div class="stars" data-review-id="1">
            <span class="star" data-value="1">&#9733;</span>
            <span class="star" data-value="2">&#9733;</span>
            <span class="star" data-value="3">&#9733;</span>
            <span class="star" data-value="4">&#9733;</span>
            <span class="star" data-value="5">&#9733;</span>
        </div>
    </div>
</form>

{% endif %}

<div class="comments">
    {% if comments %}
    <ul>
        {% for comment in comments %}
        <div class="between-comments">
            <li>
                <a href="{% url 'reviews:profile' comment.reviewer.id %}" class="user-profile-pic">
                    <img src="{{ comment.reviewer.photo }}" class="pic">
                    {{ comment.reviewer.user.username }}
                </a>
                <p class="user-comments-date">{{ comment.pub_data }}</p>
                <p>{{ comment.comment_text }}</p>
                {% for rating in comment.review.rating_set.all %}
                {% if rating.reviewer.id == comment.reviewer.id %}
                <p>Rating: {{ rating.rating_number }}</p>
                {% endif %}
                {% endfor %}
                {% if request.user.is_superuser or request.user.username == comment.reviewer.user.username %}
                <form action="{% url 'reviews:deletecomment' comment.id %}" method="get">
                    <button type="submit" class="delete-button-rvw">
                        <i class="fa fa-trash"></i>
                    </button>
                </form>
                {% endif %}
            </li>
        </div>
        {% endfor %}
    </ul>
    {% else %}
    <p>Não existem comentários.</p>
    {% endif %}
</div>

{% if error_message %}
<script>
    window.alert("{{ error_message }}");
</script>
{% endif %}
{% endblock %}